// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsmx3Gd_lsDDUYyyLZmwOPERTtr-l3hs0',
    appId: '1:380736620920:web:dd3924aad774e0c1cee08d',
    messagingSenderId: '380736620920',
    projectId: 'xenaoura-mobile',
    authDomain: 'xenaoura-mobile.firebaseapp.com',
    storageBucket: 'xenaoura-mobile.firebasestorage.app',
    measurementId: 'G-WZRTLGWG1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYxxYoCwFNtdKBEE29oe8Hsgt8sRjtss0',
    appId: '1:380736620920:android:97d0c416b5a97357cee08d',
    messagingSenderId: '380736620920',
    projectId: 'xenaoura-mobile',
    storageBucket: 'xenaoura-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU4wcDWrg2v2CB1IqQsHp1UAW-O65w6zE',
    appId: '1:380736620920:ios:31c41c9966e2501dcee08d',
    messagingSenderId: '380736620920',
    projectId: 'xenaoura-mobile',
    storageBucket: 'xenaoura-mobile.firebasestorage.app',
    iosBundleId: 'com.example.jobFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU4wcDWrg2v2CB1IqQsHp1UAW-O65w6zE',
    appId: '1:380736620920:ios:31c41c9966e2501dcee08d',
    messagingSenderId: '380736620920',
    projectId: 'xenaoura-mobile',
    storageBucket: 'xenaoura-mobile.firebasestorage.app',
    iosBundleId: 'com.example.jobFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsmx3Gd_lsDDUYyyLZmwOPERTtr-l3hs0',
    appId: '1:380736620920:web:af3912755223ee79cee08d',
    messagingSenderId: '380736620920',
    projectId: 'xenaoura-mobile',
    authDomain: 'xenaoura-mobile.firebaseapp.com',
    storageBucket: 'xenaoura-mobile.firebasestorage.app',
    measurementId: 'G-8Q3RSF6PL0',
  );

}